name: C/C++ Check

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  cpp-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang tidy
      run: sudo apt-get update && sudo apt install clang-tidy

    - name: Make - Check 
      run: make check