name: C/C++ Format

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  cpp-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang format
      run: sudo apt-get update && sudo apt install clang-format-11

    - name: Make - Format
      run: make format 