name: C/C++ Format

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  cpp-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang format
      run: sudo apt-get update && sudo apt install -y clang-format

    - name: Make - Format
      run: make format 